### PR TITLE
Collisions

### LINKED ISSUE #170: Collision memory leak
**Describe the bug**
Add a bunch of entities and then watch the ram leak

**Screenshots**

**Additional context**

### LINKED ISSUE #216: Collision improvements
Improve the collision resolution system so that collisions resolve more smoothly when two entities collide.

### PR DESCRIPTION
**Pull request by AlvinAggrey**
*changes to resolutions (Box to Box, Circle to Circle, Circle To Box)
*colliders in the centre of sprite
*Get Information of attached Entity (health, entity number, entity type)

### CODE REVIEW

**Review by kyle-robinson — CHANGES_REQUESTED** [review]
Shouldn't all of these collision changes have been made on a feature branch of the engine, and not the game?

This PR seems to bring the commit history of the game when it should really only be an addition to the engine.

You should just be able to branch off of the current engine master branch and then copy the changes that you've made specifically to the collision system.

**Comment by kyle-robinson** [comment]
_NOTE: Closing due to PR bringing commits from the game when the issue is engine-specific._

**Comment by AlvinAggrey** [comment]
Understood resolution should be on engine. However the other stuff requires the Health component which is on the game.

**Comment by kyle-robinson** [comment]
Yeah, the resolution should be on the engine, but the health component system should remain in the game. I'd say to isolate the collision resolution changes, and PR it to the engine, and then when I get around to reviewing and merging it into the engine, and then updating the game with the changes from the engine, you can add health component-specific code then - to the game that is.

I should get around to reviewing all the PRs sometime tonight, and I'll then update the game with all the changes from the master straight afterwards.

So long as you have a copy of all the changes that you've made with regard to both systems, it should be fine. But yeah, don't worry about putting the health component stuff on the engine, that should just be the collision resolution changes.

**Pull request closed without merging**
